micronaut:
  application:
    name: shelterbot

telegram:
  bot:
    name: shelter_bomb_bot
    token: XXX
    path: https://lojdk8ysb2.execute-api.us-east-1.amazonaws.com/default/ShelterBot


shelterbot:
  db:
    defaultCountry: ДНР
    defaultRegion: Донецкая
    shelters:
      ДНР-Донецкая-Андреевка: 1.csv
      ДНР-Донецкая-Донецк: 2.csv
      ДНР-Донецкая-Еленовка: 3.csv
      ДНР-Донецкая-Любовка: 4.csv
      ДНР-Донецкая-Моспино: 5.csv
      ДНР-Донецкая-Александровка: 6.csv
      ДНР-Донецкая-Луганское: 7.csv
  menu:
    perpage: 10




aws:
  accessKeyId: AKIASIGXA7LONCGDDXOE
  secretKey: XXXX
  region: us-east-1
  s3:
    botstate-bucket: shelterbot

yandex:
  geo:
    key: XXXX

google:
  geo:
    key: XXXXX