micronaut:
  application:
    name: shelterbot

telegram:
  bot:
    name: ${TELEGRAMBOTNAME}
    token: ${TELEGRAMBOTTOKEN}
    path: ${TELEGRAMBOTPATH}


shelterbot:
  db:
    defaultCountry: ДНР
    defaultRegion: Донецкая
    shelters:
      ДНР-Донецкая-Андреевка: 1.csv
      ДНР-Донецкая-Донецк: 2.csv
      ДНР-Донецкая-Еленовка: 3.csv
      ДНР-Донецкая-Любовка: 4.csv
      ДНР-Донецкая-Моспино: 5.csv
      ДНР-Донецкая-Александровка: 6.csv
      ДНР-Донецкая-Луганское: 7.csv
      ДНР-Донецкая-Горловка: 8.csv
  menu:
    perpage: 10




aws:
  accessKeyId: ${AWSACCESSKEYID}
  secretKey: ${AWSSECRETKEY}
  region: ${AWSREGION}
  s3:
    botstate-bucket: ${AWSBUCKET}

yandex:
  geo:
    key: ${YANDEXGEOKEY}

google:
  geo:
    key: ${GOOGLEGEOKEY}